[package]
name = "cbindgen-fortran"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbindgen = { git = "https://github.com/LucaCiucci/cbindgen", version = "0.25.0" }
